using CoAntiCor.Core.Domain;
using System.ComponentModel.DataAnnotations;

namespace CoAntiCor.Core.Domain.FredTicketCreation
{
    /// <summary>
    /// migrationBuilder.Sql(@"
    /// IF NOT EXISTS(SELECT* FROM sys.sequences WHERE name = 'FredRequestNumberSeq' AND SCHEMA_NAME(schema_id)= 'dbo')
    /// CREATE SEQUENCE dbo.FredRequestNumberSeq AS BIGINT START WITH 100000 INCREMENT BY 1;
    /// ");
    /// </summary>

    public class FredRequest : BaseObject
    {
        [Key]
        public Guid ID { get; set; }
        public long RequestNumber { get; set; } // generated by sequence
        public int? ResponseTimeHours { get; set; }
        [Required]
        public string Title { get; set; } = string.Empty;
        public string Priority { get; set; } = "Medium"; // Medium, High, Low  //DDL
        [Required]
        public string RequestType { get; set; } = string.Empty;   //DDL
        public string Status { get; set; } = "Open";  //DDL
        public string ProjectName { get; set; } = "GCNET";  //DDL
        [Required] 
        public string Description { get; set; } = string.Empty;

        public DateTime OpenedDate { get; set; } = DateTime.Now;
        public DateTime? TargetDeliveryDate { get; set; }
        public DateTime? CompletionDate { get; set; }

        public decimal? DevHours { get; set; }
        public string? DevOpsTicketNumber { get; set; }
        public string? WorkStream { get; set; }  //DDL
        public string? Contractual { get; set; }  //DDL
        public string? WBSCode { get; set; }
        public string? Severity { get; set; }  //DDL
        public string? SolutionType { get; set; }  //DDL

        // Platform Flags (Checkboxes)
        public bool AddPlatformNextGen { get; set; }
        public bool AddPlatformAccess { get; set; }
        public bool AddPlatformExcel { get; set; }

        public string? TeamResponse { get; set; }

        // Relationships
        //public List<ActionLog> ActionLogs { get; set; } = new();
        //public List<FileAttachment> Attachments { get; set; } = new();

        [Display(Name = "Fred Action Logs")]
        public ICollection<ActionLog> ActionLogs { get; set; } = new List<ActionLog>();
        //[Display(Name = "Fred File Attachments")]
        //public ICollection<FileAttachment>? Attachments { get; set; } = new List<FileAttachment>();
        public ICollection<FredRequestFile> Files { get; set; } = new List<FredRequestFile> { };
    }

}
