using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CoAntiCor.Core.Domain;
using CoAntiCor.Core.DTO;
using CoAntiCor.Core.Interfaces;
using CoAntiCor.Core.Model;
using CoAntiCor.Core.Services;
using CoAntiCor.Infrastructure.Context;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using System;

namespace CoAntiCor.API.Services
{
    public class CaseFilePdfService : ICaseFilePdfService
    {
        /*  public async Task<CaseFileBundle> GenerateAsyncNew(
                  Guid offerId,
                  CoAntiCorDbContext db,
                  IContractPdfService contractPdf)
          {
              var lifecycle = await db.GetLifecycleAsync(offerId);
              if (lifecycle is null)
                  throw new Exception("Offer not found");

              var pdfBytes = Document.Create(container =>
              {
                  container.Page(page =>
                  {
                      page.Margin(40);
                      page.Size(PageSizes.A4);

                      page.Header().Element(header =>
                      {
                          Helper.PageHeader(header, lifecycle);
                      });

                      page.Content().Element(content =>
                      {
                          Helper.PageLifecycle(content, lifecycle);
                      });

                      page.Footer().AlignCenter().Text(txt =>
                      {
                          txt.Span("Generated by CoAntiCor CaseFile Engine");
                      });
                  });
              })
              .GeneratePdf();

              var fileName = $"CaseFile-{offerId}.pdf";

              return new CaseFileBundle { PdfBytes = pdfBytes, FileName = fileName };

          }

          public async Task<CaseFileBundle> GenerateAsync(
              Guid offerId,
              CoAntiCorDbContext db,
              IContractPdfService contractPdf)
          {
              var offer = await db.Offers
                  .Include(o => o.Property)
                  .Include(o => o.Contract)
                  .FirstAsync(o => o.Id == offerId);

              var lifecycle = await db.GetLifecycleAsync(offerId); // reuse your lifecycle query
              var audits = await db.SignatureAudits
                  .Where(a => a.ContractId == offer.Contract!.Id)
                  .OrderBy(a => a.OccurredAtUtc)
                  .ToListAsync();

              var contractPdfBytes = contractPdf.Generate(offer.Contract!);

              var doc = Document.Create(container =>
              {
                  container.Page(page =>
                  {
                      page.Margin(40);
                      page.Content().Column(col =>
                      {
                          col.Item().Text("Regulator Case File").FontSize(20).Bold();
                          col.Item().Text($"Offer: {offer.Id}");
                          col.Item().Text($"Property: {offer.Property.Address}, {offer.Property.City}");
                          col.Item().Text($"Buyer: {offer.BuyerName}  Seller: {offer.SellerName}");
                          col.Item().Text($"Price: {offer.OfferedPrice} {offer.Currency}");
                          col.Item().Text($"Created: {offer.CreatedAtUtc:O}");
                      });
                      pageLifecycle(page, lifecycle);
                      pagePayments(page, lifecycle);
                      pageCadastre(page, lifecycle);
                      pageSplits(page, lifecycle);
                      pageAudit(page, audits);
                  });

                  //pageLifecycle(page, lifecycle);
                  //pagePayments(page, lifecycle);
                  //pageCadastre(page, lifecycle);
                  //pageSplits(page, lifecycle);
                  //pageAudit(page, audits);
              });

              var bundleBytes = doc.GeneratePdf();
              var fileName = $"CaseFile-{offer.Id}.pdf";

              return new CaseFileBundle { PdfBytes = bundleBytes, FileName = fileName };

              static void pageLifecycle(PageDescriptor page, ContractLifecycleDto lifecycle)
              {
                  page.Margin(40);
                  page.Content().Column(col =>
                  {
                      col.Item().Text("Lifecycle").FontSize(16).Bold();
                      col.Item().Text($"Contract: {lifecycle.ContractId}");
                      col.Item().Text($"Status: {lifecycle.ContractStatus}");
                      col.Item().Text($"BuyerSignedAt: {lifecycle.BuyerSignedAtUtc}");
                      col.Item().Text($"SellerSignedAt: {lifecycle.SellerSignedAtUtc}");
                  });
              }

              static void pagePayments(PageDescriptor page, ContractLifecycleDto lifecycle)
              {
                  page.Margin(40);
                  page.Content().Column(col =>
                  {
                      col.Item().Text("Payments").FontSize(16).Bold();
                      foreach (var p in lifecycle.Payments)
                      {
                          col.Item().Text(
                              $"{p.Timestamp:O}  {p.Label}  {p.Amount} {p.Currency}  {p.Status}  Ref:{p.GatewayRef}");
                      }
                  });
              }

              static void pageCadastre(PageDescriptor page, ContractLifecycleDto lifecycle)
              {
                  page.Margin(40);
                  page.Content().Column(col =>
                  {
                      col.Item().Text("Cadastre Checks").FontSize(16).Bold();
                      foreach (var c in lifecycle.CadastreEvents)
                      {
                          col.Item().Text(
                              $"{c.CheckedAtUtc:O}  {(c.IsValid ? "Valid" : "Invalid")}  {c.Message}");
                      }
                  });
              }

              static void pageSplits(PageDescriptor page, ContractLifecycleDto lifecycle)
              {
                  page.Margin(40);
                  page.Content().Column(col =>
                  {
                      col.Item().Text("Land Splits").FontSize(16).Bold();
                      foreach (var s in lifecycle.LandSplits)
                      {
                          col.Item().Text($"{s.CreatedAtUtc:O}  {s.Status}  {s.Id}");
                      }
                  });
              }

              static void pageAudit(PageDescriptor page, List<SignatureAudit> audits)
              {
                  page.Margin(40);
                  page.Content().Column(col =>
                  {
                      col.Item().Text("Signature Audit Trail").FontSize(16).Bold();
                      foreach (var a in audits)
                      {
                          col.Item().Text(
                              $"{a.OccurredAtUtc:O}  {a.ActorRole}({a.ActorUserId})  {a.Action}  IP:{a.IpAddress}");
                      }
                  });
              }
          }
        */
        Task<CaseFileBundle> ICaseFilePdfService.GenerateAsync(Guid offerId, CoAntiCorDbContext db, IContractPdfService contractPdf)
        {
            throw new NotImplementedException();
        }
    }
}
