<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-CoAntiCor.App.App-c6d90862-6796-458a-9e7c-d56e39862649</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Shared\SharedResource.fr.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Shared\SharedResource.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Templates\" />
    <Folder Include="wwwroot\uploads\temp\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoAntiCor.API\CoAntiCor.API.csproj" />
    <ProjectReference Include="..\CoAntiCor.Core\CoAntiCor.Core.csproj" />
  </ItemGroup>

</Project>
